projects:
 # You can add multiple projects and generate with -p args
 default:
 # 👇 For vscode-graphql and intellisense
 schema:
 - ./src/lib/modules/**/typedefs/*.graphql
 - ./$houdini/graphql/schema.graphql
 documents:
 - ./src/lib/modules/**/graphql/*.gql
 - ./$houdini/graphql/documents.gql

 # 👇 For code generation
 extensions:
 codegen:
 generates:
 ./src/lib/graphql/$kitql/graphqlTypes.ts:
 plugins:
 - typescript

 ./src/lib/modules/:
 preset: graphql-modules
 presetConfig:
 baseTypesPath: ../graphql/$kitql/graphqlTypes.ts
 importBaseTypesFrom: $graphql/$kitql/graphqlTypes
 filename: $kitql/moduleTypes.ts
 plugins:
 - typescript
 - typescript-resolvers
 config:
 contextType: $graphql/kitQLServer#IKitQLContext
 useTypeImports: true
